import 'package:tasks/features/todo/domain/entities/todo_entity.dart';
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'todo_model.mapper.dart';

@MappableClass()
class TodoModel extends TodoEntity with TodoModelMappable {
  TodoModel({
    super.id,
    required super.title,
    super.description,
    @MappableField(key: 'is_done') super.isDone,
    @MappableField(key: 'created_at') super.createdAt,
    @MappableField(key: 'updated_at') super.updatedAt,
  });
}
